name: 'Bulk Merge'
description: 'Merge pull requests that match given criteria'
inputs:
  repo-token:
    description: 'The authentication token to use'
    required: true
    default: ${{ secrets.GITHUB_TOKEN }}

  authors:
    description: 'The list of authors that should be merged'
    required: false

  title:
    description: 'Regex the title must match'
    required: false
    default: '.*'

runs:
  using: 'node16'
  main: 'dist/index.js'
